= Автоматическое создание визиток
Марк Сафронов <hijarian@gmail.com>
v1.0, {docdatetime}
:toc:

Здесь лежат два скрипта, которые я когда-то сделал для того, чтобы упростить жене автоматическую генерацию макетов визиток из присланных экселевских файлов от клиента. Макеты делаются в Adobe Illustrator CS6, и сохраняются в EPS и PDF.

== Подготовка

Нам нужны следующие вещи:

* Скрипты `BusinessCards.jsx` и `ExportBusinessCards.jsx`. Кладём их в папку скриптов Adobe Illustrator. Для Creative Suite 6 на Windows 7 x64 это `C:\Program Files\Adobe\Adobe Illustrator CS6 (64 Bit)\Presets\en_US\Scripts`. Так мы сможем запускать их через `File` -> `Scripts`.

* Шаблон визитки, полностью оформленный, неважно в каком формате, лишь бы его Illustrator открывал. В этом шаблоне должны быть определены четыре текстовых фрейма. У этих фреймов должны быть через панель Layers выставлены следующие имена:

** "Контакты"
** "Адрес"
** "Должность"
** "ФИО"

* Исходная таблица с данными, сохранённая из Excel в формате CSV. В таблице должны быть следующие колонки:

** "Фамилия"
** "Имя Отчество"
** "Должность"
** "Адрес"
** "Телефоны"
** "Электронная почта"
** "Skype"

Задача, фактически, поля таблицы воткнуть в поля на макете. *Очень важно* чтобы CSV был сохранён именно из Excel, потому что скрипт подогнан под форматирование, которое делает именно эта программа: разделитель - точка с запятой, строки в кавычках.

Примеры исходных данных в папке `example/datasource`.

Примеры шаблонов в папке `example/templates`.

== Автоматизация рабочего процесса

. Открываем шаблон.
. File -> Scripts -> BusinessCards.
. Открывается диалог выбора файла. Указываем там желаемый файл с данными, в CSV.
. Открывается диалог выбора папки. Указываем там папку, куда будут сохранены обработанные визитки.
. После выбора папки скрипт сразу начинает работать. Для каждой строчки из CSV будет открыта отдельная копия шаблона и очищенные данные из таблицы будет вставлены в макет.
. Вручную просматриваем полученные макеты, выравниваем тексты, исправляем то, что автоматическая очистка не смогла.
. File -> Scripts -> ExportBusinessCards.
. Каждый из открытых макетов по одному начинает сохраняться в папку, указанную в начале процесса. Создаётся два файла: 
  * один в том же формате, что и исходный шаблон, с текстом, преобразованным в кривые
  * другой в формате PDF, с исходным текстом.
. Всё.
